### ISSUE TITLE
Plagariasm (checkio.org)

### ISSUE THREAD

**Issue by k3n** [ryanmcdermott/clean-code-javascript#231]
Thought you'd want to know:

https://js.checkio.org/blog/javascript-best-practices-function/

**Comment by jljorgenson18** [comment]
This was a blatant rip off as well https://blog.risingstack.com/javascript-clean-coding-best-practices-node-js-at-scale/.

**Comment by ryanmcdermott** [comment]
Thanks for your detective work! It's unfortunate for the contributors that they are not receiving credit by a link back to this repo. I'll leave a kind request for these blogs when I get the chance.

**Comment by AnaRobynn** [comment]
In all honesty, MIT licence doesn't say anything about this. Only that the licence itself should be included in the used code.

In that sense it's fine to use and publish the code as is. As long as they publish it with the same licence. They don't have to link the repo at all. It's nice practice, but under MIT it's not a obligation. If I'm wrong, please ping me, because licensing is hard to understand.

**Comment by ryanmcdermott** [comment]
At the end of the day, I'm just happy that people are learning and writing better code. Recognition is nice, but this project has exceeded all of my expectations.

Thanks!
