### ISSUE TITLE
'Use getters and setters' inconsistency

### ISSUE THREAD

**Issue by vsemozhetbyt** [ryanmcdermott/clean-code-javascript#45]
> // It doesn't have to be prefixed with `get` or `set` to be a getter/setter

Well, how we can distinguish them from methods? With the example used there, the heading should be 'Prefer methods to simple properties and getters / setters'.

**Comment by cookiengineer** [comment]
The problem in JS (ES5.1+) is that setters and getters need a wrapping scope or variable for type validation. So you have multiple "private properties" if you want to do complex validations.

So I kind of agree with @ryanmcdermott but I'm personally using always explicit `setWhatever(whatever)` method names on the prototype, so I can directly figure out where it came from and what it does.

If I want to use Composite Pattern, I am typically using them directly for read-access, e.g. `let whatever = this.whatever` instead of using `getWhatever()` calls all the time due to performance downsides of function calls. His example kind of implies that states of the Composite are always functionally changed (e.g. via the verbs `withdraw(amount)` or `calculate(amount)` instead of `setBalance(calculated)`).

**Comment by vsemozhetbyt** [comment]
I mean, the heading is about getters/setters and the example is about methods, they have different ways to be addressed (simple evaluation with operators vs function calls), so this is somehow confusing.

**Comment by ryanmcdermott** [comment]
Fixed in #101
