### ISSUE TITLE
Suggest url,filename mvc architecture file names?

### ISSUE THREAD

**Issue by gsivaprabu** [ryanmcdermott/clean-code-javascript#59]
Hi @ryanmcdermott ,

This is **not an issue**, How to we given the filenames is ***lowerCamelCase ,UpperCamelCase, file_name.js , file-name.js*** like that and standard format is there ?

If  we request api call means how we mention the url ?

Request URL:https://serviceprovider.com/api/power-details
Request URL:https://serviceprovider.com/api/power_details
Request URL:https://serviceprovider.com/api/powerDetails
Request URL:https://serviceprovider.com/api/Powerdetails

like the above any standard ?

If we create an MVC architecture means how we use this file name

Model
	- loginModel.html
	- login-model.html
	- login_model.html
Views
	- loginView.js
	- login-iew.js
	- login_view.js
Controller
	- loginController.js
	- login-Controller.js
	- login_Controller.js

If we create url means how we use ?

Please suggest **standard** format

**Comment by CodinCat** [comment]
I don't think there is a **standard format**, it's just a matter of personal taste (or a team). You can use whatever you want if your team members agreed.

**Comment by JefferyHus** [comment]
URLs must be clear for a SEO purpose, file's name depends on you and your team is there is one, but the more you are clean the easy to know where your code lives.

**Comment by ryanmcdermott** [comment]
Hi there Sivaprabu! Clean Code doesn't get into this specifically, since this would be a team choice, as mentioned by @CodinCat. 

The document as a whole serves to codify some already existing JavaScript practices and adapt other ones from Clean Code, that improve readability, reusability, and refactorability. Choices that are subjective conventions, such as filename formats, end up not having clear and justifiably better choices. Just as formatting conventions like tabs vs. spaces don't have a justifiable winner, it's a matter of team preference. Arguing otherwise is a waste of developer time, in my opinion!

Thanks so much for looking into this though, keep opening up issues!
