### ISSUE TITLE
"If Haskell were an IPA ..."

### ISSUE THREAD

**Issue by x1024** [ryanmcdermott/clean-code-javascript#75]
From the guide: "If Haskell were an IPA then JavaScript would be an O'Douls."

I have no idea what you're talking about. JS programmers aren't required to know beer brands, let alone country-specific beer brands.  A user that doesn't know where Haskell and JS stood on the functional spectrum would be pretty lost here.

In general, a programming guide should require zero knowledge outside the field of programming.

If the comparison just *has* to be there, here's a suggestion:  
"If Haskell were a good steak, then JS would be a sandwich with slices of meat.

**Comment by Ribesg** [comment]
Had no idea what this meant, I just ignored the sentence entirely. It should not be here or be replaced with something understandable.

**Comment by vsemozhetbyt** [comment]
I think this is a matter of taste. I've googled it and I've found it funny, Even some very serious developers make fun breaks in their researches or lectures (see 'Cuteness breaks' [here](http://benediktmeurer.de/2016/12/16/the-truth-about-traditional-javascript-benchmarks/)). I see no harm in these breaks to use less common information. It is like reading a book of William Gibson or Neal Stephenson or something.

**Comment by ryanmcdermott** [comment]
Since a few people are airing some confusions here, and I appreciate that, let me explain some of the stylistic choices in this document: I've tried to make this as fun and easily understandable as possible. As for the former point, I'm not sure how fun it is to read but it was certainly fun for me to write! 

These little quips are for the purposes of "fun", as they break up some of the tedium that people may feel while reading an architectural and best practices text. Now, if some of these light-hearted references are falling flat and distracting people from the overall meaning of the text, then they aren't doing their job. In retrospect, beer types and brands aren't universally understood! Having said that though, I'd hesitate to say there will be anything that could be expected to universally understood outside the field of programming, as we can't even expect everyone to understand everything inside the field of programming itself! 

As it is, making references to things outside programming can help ground the concepts you are learning about. Abstract concepts stick so much better when related to something real and tangible you already know. However, since this little beer joke doesn't help anything be more easily understood and can be removed without affecting the meaning of the subsection, I will get rid of it. That's cleaner after all 😉 .

Thanks for helping @x1024! The clearer we can make this for the broadest audience possible, the better!

**Comment by ryanmcdermott** [comment]
Closed after: d28b1e3c2f8f0df82160362376d5775f5cc3596c
